replicaCount: 0

image:
  repository: selcpacr.azurecr.io/selfcaremsonboardinginterceptor
  pullPolicy: Always # TODO change me in IfNotPresent when each build will have a different tag
  tag: 1.0-SNAPSHOT

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://selfcare.pagopa.it"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

pdb:
  enabled: false
  minAvailable: 2

configEnvSpecific:
  INTERNAL_API_SERVICE_URL: "https://api.selfcare.pagopa.it"