replicaCount: 2

image:
  repository: selcdacr.azurecr.io/selfcaremsonboardinginterceptor

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://dev.selfcare.pagopa.it,http://localhost:3000"
  tls:
    - hosts:
        - selc.internal.dev.selfcare.pagopa.it
      secretName: selc-internal-dev-selfcare-pagopa-it
  hosts:
    - host: selc.internal.dev.selfcare.pagopa.it
      paths:
        - path: /ms-onboarding-interceptor/(.*)
          pathType: ImplementationSpecific

resources:
  requests:
    cpu: 300m
    memory: 500M
  limits:
    cpu: 600m
    memory: 800M

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

pdb:
  enabled: true

configEnvSpecific:
  INTERNAL_API_SERVICE_URL: "https://api.dev.selfcare.pagopa.it"
